// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jwutbnzqibfxfvocafkl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp3dXRibnpxaWJmeGZ2b2NhZmtsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMzY2MjcsImV4cCI6MjA2OTcxMjYyN30.c9SZ8jgK6giasnDybVBt6tyhn9ZrGM7cB6k8GoKHhu0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});